/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import caballero.practico7.*;
import java.util.HashSet;

/**
 *
 * @author Guido Caballero
 */
public class ViewPrincipal extends javax.swing.JFrame {

    private static HashSet <Materia> materias = new HashSet<>();
    private static HashSet <Alumno> alumnos = new HashSet<>();

    public static HashSet<Materia> getMaterias() {
        return materias;
    }
    public static HashSet<Alumno> getAlumnos() {
        return alumnos;
    }

    public static void setMaterias(HashSet<Materia> m) {
        ViewPrincipal.materias = m;
    }
    public static void setAlumnos(HashSet<Alumno> a) {
        ViewPrincipal.alumnos = a;
    }
    
    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmMaterias = new javax.swing.JMenu();
        jmNewMateria = new javax.swing.JMenuItem();
        jmNewAlumno = new javax.swing.JMenuItem();
        jmInscripcion = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 700));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jmMaterias.setText("Inicio");
        jmMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMateriasActionPerformed(evt);
            }
        });

        jmNewMateria.setText("Nueva Materia");
        jmNewMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmNewMateriaActionPerformed(evt);
            }
        });
        jmMaterias.add(jmNewMateria);

        jmNewAlumno.setText("Nuevo Alumno");
        jmNewAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmNewAlumnoActionPerformed(evt);
            }
        });
        jmMaterias.add(jmNewAlumno);

        jmInscripcion.setText("Inscribir Alumnos");
        jmInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmInscripcionActionPerformed(evt);
            }
        });
        jmMaterias.add(jmInscripcion);

        jmSalir.setText("Salir");
        jmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalirActionPerformed(evt);
            }
        });
        jmMaterias.add(jmSalir);

        jMenuBar1.add(jmMaterias);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMateriasActionPerformed
    }//GEN-LAST:event_jmMateriasActionPerformed

    private void jmNewAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmNewAlumnoActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        ViewAlumno va = new ViewAlumno();
        va.setVisible(true);
        jDesktopPane1.add(va);
        jDesktopPane1.moveToFront(va);
    }//GEN-LAST:event_jmNewAlumnoActionPerformed
    private void jmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jmSalirActionPerformed
    private void jmNewMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmNewMateriaActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        ViewMaterias vm = new ViewMaterias();
        vm.setVisible(true);
        jDesktopPane1.add(vm);
        jDesktopPane1.moveToFront(vm);
    }//GEN-LAST:event_jmNewMateriaActionPerformed
    private void jmInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmInscripcionActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        ViewInscripcion vi = new ViewInscripcion();
        vi.setVisible(true);
        jDesktopPane1.add(vi);
        jDesktopPane1.moveToFront(vi);
    }//GEN-LAST:event_jmInscripcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmInscripcion;
    private javax.swing.JMenu jmMaterias;
    private javax.swing.JMenuItem jmNewAlumno;
    private javax.swing.JMenuItem jmNewMateria;
    private javax.swing.JMenuItem jmSalir;
    // End of variables declaration//GEN-END:variables
}
